add_library(uv_cgi_lib
    Cookie.cpp
    Cookie.h
    CookieJar.cpp
    CookieJar.h
    Environment.cpp
    Environment.h
    File.cpp
    File.h
    Headers.cpp
    Headers.h
    Info.cpp
    Info.h
    Input.cpp
    Input.h
    ISessionStorage.h
    Params.cpp
    Params.h
    Post.cpp
    Post.h
    Request.cpp
    Request.h
    Response.cpp
    Response.h
    Session.cpp
    SessionFileStorage.cpp
    SessionFileStorage.h
    Session.h
    Url.cpp
    Url.h
)
target_link_libraries(uv_cgi_lib uv_core_lib hashlibpp)
target_include_directories(uv_cgi_lib PRIVATE ${PROJECT_INCLUDE_DIRS})
